import type { Player, TerrainType } from "gameCore/gameResources/src";

export const testPlayer: Player = {
  name: "muzzle",
  race: "chimeras",
  fraction: "dark",
  obsidian: 1000,
  recources: {
    gold: 1000,
    wood: 1000,
    stone: 1000,
    grain: 1000,
    iron: 1000,
    population: 1000,
  },
};

export const kingdom_map: TerrainType[] = [
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "steppe",
  "steppe",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "steppe",
  "hollyLand",
  "steppe",
  "deadLand",
  "deadLand",
  "deadLand",
  "deadLand",
  "steppe",
  "steppe",
  "steppe",
  "hollyLand",
  "steppe",
  "deadLand",
  "deadLand",
  "deadLand",
  "steppe",
  "steppe",
  "steppe",
  "hollyLand",
  "hollyLand",
  "steppe",
  "steppe",
  "steppe",
  "deadLand",
  "steppe",
  "hollyLand",
  "hollyLand",
  "hollyLand",
  "hollyLand",
  "steppe",
  "steppe",
  "steppe",
  "steppe",
  "steppe",
  "steppe",
  "magicForest",
  "hollyLand",
  "hollyLand",
  "steppe",
  "steppe",
  "steppe",
  "steppe",
  "steppe",
  "steppe",
  "magicForest",
  "magicForest",
  "magicForest",
];
